dependencies {
    implementation libs.sfm.csv
    implementation libs.excel.streaming.reader
    implementation libs.commons.lang3
    implementation libs.commons.io
    implementation project(':backend:molgenis-emx2')
    implementation project(':backend:molgenis-emx2-tasks')
    testImplementation project(':backend:molgenis-emx2-sql')
    testImplementation project(':backend:molgenis-emx2-datamodels')
}
