"""
Constant column type metadata.
"""

_ARRAY = "_ARRAY"
HEADING = "HEADING"
LOGO = "LOGO"
STRING = "STRING"
TEXT = "TEXT"
INT = "INT"
DECIMAL = "DECIMAL"
BOOL = "BOOL"
HYPERLINK = "HYPERLINK"
DATE = "DATE"
DATETIME = "DATETIME"

STRING_ARRAY = STRING + _ARRAY
TEXT_ARRAY = TEXT + _ARRAY
INT_ARRAY = INT + _ARRAY
DECIMAL_ARRAY = DECIMAL + _ARRAY
BOOL_ARRAY = BOOL + _ARRAY
DATE_ARRAY = DATE + _ARRAY
DATETIME_ARRAY = DATETIME + _ARRAY
HYPERLINK_ARRAY = HYPERLINK + _ARRAY

NONREFS = [STRING, TEXT, INT, DECIMAL, BOOL, DATE, DATETIME, HYPERLINK,
           STRING_ARRAY, TEXT_ARRAY, INT_ARRAY, DECIMAL_ARRAY, BOOL_ARRAY, DATE_ARRAY, DATETIME_ARRAY, HYPERLINK_ARRAY]
