FROM eclipse-temurin:17.0.11_9-jdk-jammy
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENV MOLGENIS_OIDC_CLIENT_ID=$MOLGENIS_OIDC_CLIENT_ID
ENV MOLGENIS_OIDC_CLIENT_SECRET=$MOLGENIS_OIDC_CLIENT_SECRET
ENV MOLGENIS_OIDC_CLIENT_NAME=$MOLGENIS_OIDC_CLIENT_NAME
ENV MOLGENIS_OIDC_DISCOVERY_URI=$MOLGENIS_OIDC_DISCOVERY_URI
ENV MOLGENIS_OIDC_CALLBACK_URL=$MOLGENIS_OIDC_CALLBACK_URL
EXPOSE 8080
RUN apt-get update && apt-get install python3 python3-venv -y
ENTRYPOINT ["java","-jar","app.jar"]
