/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./nuxt.config.{js,ts}",
    "./*.vue",
  ],
  safelist: [
    {
      pattern: /^bg-/,
    },
    {
      pattern: /^text-/,
    },
    {
      pattern: /^border-/,
    },
    {
      pattern: /^antialiased/,
    },
  ],
  theme: {
    fontFamily: {
      display: ["Bebas Neue", "sans-serif"],
      sans: ["IBM Plex Sans", "sans-serif"],
      mono: "monospace",
    },
    fontSize: {
      "heading-7xl": ["3.75rem", "1.2"],
      "heading-6xl": ["3rem", "1.2"],
      "heading-5xl": ["2.1875rem", "1.2"],
      "heading-4xl": ["1.875rem", "1.2"],
      "heading-3xl": ["1.5625rem", "1.2"],
      "heading-2xl": ["1.375rem", "1.2"],
      "heading-xl": ["1.25rem", "1.2"],
      "heading-lg": ["1.125rem", "1.2"],
      "heading-base": ["1rem", "1.2"],
      "heading-sm": ["0.875rem", "1.2"],
      "body-lg": ["1.125rem", "1.8"],
      "body-base": ["1rem", "1.8"],
      "body-sm": ["0.875rem", "1.8"],
      "body-xs": ["0.75rem", "1.5"],
    },
    colors: {
      current: "currentColor",
      black: "#333",
      white: "#fff",
      transparent: "transparent",
      blue: {
        50: "var(--color-blue-50)",
        100: "var(--color-blue-100)",
        200: "var(--color-blue-200)",
        300: "var(--color-blue-300)",
        500: "var(--color-blue-500)",
        700: "var(--color-blue-700)",
        800: "var(--color-blue-800)",
      },
      gray: {
        100: "#F4F4F4",
        200: "#E2E2E2",
        400: "#C0C0C0",
        600: "#6D6D6D",
        900: "#1D1D1D",
      },
      yellow: {
        200: "#FFF4CB",
        500: "#FFF500",
        800: "#C89B00",
      },
      green: {
        500: "#72F6B2",
        800: "#349D63",
      },
      orange: {
        500: "#E1B53E",
      },
      red: {
        500: "#E14F62",
        700: "#AE2A3F",
      },
    },
    extend: {
      boxShadow: ({ theme }) => ({
        primary: "var(--box-shadow-primary)",
        "input-hover": "var(--box-shadow-input-hover)",
        "search-input": "var(--box-shadow-search-input)",
        "pagination-gray": "var(--box-shadow-pagination-gray)",
      }),
      spacing: {
        "3px": "3px",
        "50px": "50px",
        18: "4.5rem",
        19: "4.75rem",
        7.5: "1.875rem",
        8.75: "2.1875rem",
        10.5: "2.625rem",
        12.5: "3.125rem",
        15: "3.75rem",
        25: "6.25rem",
        95: "23.75rem",
        82.5: "20.625rem",
      },
      minWidth: {
        95: "23.75rem",
      },
      maxHeight: {
        title: "10rem",
      },
      minHeight: {
        title: "10rem",
      },
      maxWidth: {
        lg: "88.75rem", // 970+380+30+20+20
        tooltip: "10.5rem",
        none: "none",
        sm: "20rem",
        xs: "15rem",
        table: "60.7rem",
        title: "10rem",
      },
      transitionDuration: {
        default: "500",
      },
      backgroundImage: {
        "sidebar-gradient": "var(--background-image-sidebar-gradient)",
        "base-gradient": "var(--background-image-base-gradient)",
        "collapsible-listitem-line":
          "url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0nMjAnIGhlaWdodD0nMjQnIHZpZXdCb3g9JzAgMCAyMCAyMicgZmlsbD0nbm9uZScgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJz48cGF0aCBkPSdNMSAxVjIxJyBzdHJva2U9JyM4QkM1RkYnIHN0cm9rZS1saW5lY2FwPSdyb3VuZCcgc3Ryb2tlLWxpbmVqb2luPSdyb3VuZCcgc3Ryb2tlLWRhc2hhcnJheT0nNCA0Jy8+PC9zdmc+Cg==)",
      },
      backgroundColor: ({ theme }) => ({
        "button-primary": "var(--background-color-button-primary)",
        "button-primary-hover": "var(--background-color-button-primary-hover)",
        "button-secondary": "var(--background-color-button-secondary)",
        "button-secondary-hover":
          "var(--background-color-button-secondary-hover)",
        "button-tertiary": "var(--background-color-button-tertiary)",
        "button-tertiary-hover":
          "var(--background-color-button-tertiary-hover)",
        "button-outline": "var(--background-color-button-outline)",
        "button-outline-hover": "var(--background-color-button-outline-hover)",
        "button-disabled": "var(--background-color-button-disabled)",
        "button-disabled-hover": "var(background-color-button-disabled-hover)",
        "button-filter": "var(--background-color-button-filter)",
        "button-filter-hover": "var(--background-color-button-filter-hover)",
        "button-tree-node-toggle":
          "var(--background-color-button-tree-node-toggle)",
        "search-button": "var(--background-color-search-button)",
        "search-button-hover": "var(--background-color-search-button-hover)",
        navigation: "var(--background-color-navigation)",
        "navigation-sticky": "var(--background-color-navigation-sticky)",
        "search-results-view-tabs":
          "var(--background-color-search-results-view-tabs)",
        "search-filter-group-toggle":
          "var(--background-color-search-filter-group-toggle)",
        "app-wrapper": "var(--background-color-app-wrapper)",
        pagination: "var(--background-color-pagination)",
        "pagination-hover": "var(--background-color-pagination-hover)",
        form: "var(--background-color-form)",
        "form-legend": "var(--background-color-form-legend)",
        footer: "var(--background-color-footer)",
        "form-required": "var(--background-color-form-required)",
        "form-required-btn": "var(--background-color-form-required-btn)",
        "form-required-btn-hover":
          "var(--background-color-form-required-btn-hover)",
        modal: "var(--background-color-modal)",
        footer: "var(--background-color-footer)",
        "modal-footer": "var(--background-color-modal-footer)",
        tab: "var(--background-color-tab)",
        "tab-hover": "var(--background-color-tab-hover)",
        "tab-active": "var(--background-color-tab-active)",

        valid: "var(--color-valid-background)",
        invalid: "var(--color-invalid-background)",
        disabled: "var(--color-disabled-background)",
        neutral: "var(--color-neutral-background)",

        input: "var(--background-color-input)",
        listbox: "var(--background-color-listbox)",
        "listbox-hover": "var(--background-color-listbox-hover)",
        "listbox-selected": "var(--background-color-listbox-selected)",
        table: "var(--background-color-table)",
        hover: "var(--background-color-hover)",
        notification: "var(--background-color-notification)",
        valid: "var(--color-valid-background)",
        invalid: "var(--color-invalid-background)",
        disabled: "var(--color-disabled-background)",
        neutral: "var(--color-neutral-background)",
        input: "var(--background-color-input)",
        "input-focused": "var(--background-color-input-focused)",
        "input-checked": "var(--background-color-button-primary)",
        notification: "var(--background-color-notification)",
        "code-output": "var(--background-color-code-output)",
      }),
      textColor: ({ theme }) => ({
        "button-primary": "var(--text-color-button-primary)",
        "button-primary-hover": "var(--text-color-button-primary-hover)",
        "button-secondary": "var(--text-color-button-secondary)",
        "button-secondary-hover": "var(--text-color-button-secondary-hover)",
        "button-tertiary": "var(--text-color-button-tertiary)",
        "button-tertiary-hover": "var(--text-color-button-tertiary-hover)",
        "button-outline": "var(--text-color-button-outline)",
        "button-outline-hover": "var(--text-color-button-outline-hover)",
        "button-disabled": "var(--text-color-button-disabled)",
        "button-disabled-hover": "var(--text-color-button-disabled-hover)",
        "button-filter": "var(--text-color-button-filter)",
        "button-text": "var(--text-color-button-text)",
        menu: "var(--text-color-menu)",
        "button-tree-node-toggle": "var(--text-color-button-tree-node-toggle)",
        "button-tree-node-toggle-hover":
          "var(--text-color-button-tree-node-toggle-hover)",
        menu: "var(--text-color-menu)",
        "sub-menu": "var(--text-color-sub-menu)",
        "sub-menu-hover": "var(--text-color-sub-menu-hover)",
        "breadcrumb-arrow": "var(--text-color-breadcrumb-arrow)",
        breadcrumb: "var(--text-color-breadcrumb)",
        title: "var(--text-color-title)",
        "title-contrast": "var(--text-color-title-contrast)",
        "title-contrast-pop": "var(--text-color-title-contrast-pop)",
        "sub-title-contrast": "var(--text-color-sub-title-contrast)",
        "search-button": "var(--text-color-search-button)",
        "search-button-hover": "var(--text-color-search-button-hover)",
        favorite: "var(--text-color-favorite)",
        "favorite-hover": "var(--text-color-favorite-hover)",
        "search-results-view-tabs":
          "var(--text-color-search-results-view-tabs)",
        "search-results-view-tabs-hover":
          "var(--text-color-search-results-view-tabs-hover)",
        "search-filter-title": "var(--text-color-search-filter-title)",
        "search-filter-expand": "var(--text-color-search-filter-expand)",
        "search-filter-expand-mobile":
          "var(--text-color-search-filter-expand-mobile)",
        "search-filter-group-title":
          "var(--text-color-search-filter-group-title)",
        "search-filter-group-title-mobile":
          "var(--text-color-search-filter-group-title-mobile)",
        "search-filter-group-checkbox":
          "var(--text-color-search-filter-group-checkbox)",
        "search-filter-group-toggle":
          "var(--text-color-search-filter-group-toggle)",
        "search-filter-title-inverted":
          "var(--text-color-search-filter-title-inverted)",
        "search-filter-expand-inverted":
          "var(--text-color-search-filter-expand-inverted)",
        "search-filter-group-title-inverted":
          "var(--text-color-search-filter-group-title-inverted)",
        "search-filter-group-checkbox-inverted":
          "var(--text-color-search-filter-group-checkbox-inverted)",
        "search-filter-group-toggle-inverted":
          "var(--text-color-search-filter-group-toggle-inverted)",
        "tooltip-hover-dark": "var(--text-color-tooltip-hover-dark)",
        "tooltip-hover-light": "var(--text-color-tooltip-hover-light)",
        pagination: "var(--text-color-pagination)",
        "pagination-inverted": "var(--text-color-pagination-inverted)",
        "pagination-input": "var(--text-color-pagination-input)",
        "pagination-hover": "var(--text-color-pagination-hover)",
        "pagination-button": "var(--text-color-pagination-button)",
        "pagination-button-hover": "var(--text-color-pagination-button-hover)",
        link: "var(--text-color-link)",
        "table-column-header": "var(--text-color-table-column-header)",
        "table-row": "var(--text-color-table-row)",
        "form-header": "var(--text-color-form-header)",

        input: "var(--text-color-input)",
        "input-description": "var(--text-color-input-description)",

        required: "var(--text-color-required)",
        listbox: "var(--text-color-listbox)",
        "listbox-hover": "var(--text-color-listbox-hover)",
        "listbox-selected": "var(--text-color-listbox-selected)",
        "input-checked": "var(--text-color-button-primary)",
        "input-focused": "var(--text-color-button-primary)",

        invalid: "var(--color-invalid-foreground)",
        neutral: "var(--color-neutral-foreground)",
        valid: "var(--color-valid-foreground)",
        disabled: "var(--color-disabled-foreground)",

        required: "var(--text-color-required)",
        "button-input-toggle": "var(--text-color-button-input-toggle)",
        "legend-error-count": "var(--text-color-legend-error-count)",
        "code-output": "var(--text-color-code-output)",
      }),
      borderColor: ({ theme }) => ({
        theme: "var(--border-color-theme)",
        "button-primary": "var(--border-color-button-primary)",
        "button-primary-hover": "var(--border-color-button-primary-hover)",
        "button-secondary": "var(--border-color-button-secondary)",
        "button-secondary-hover": "var(--border-color-button-secondary-hover)",
        "button-tertiary": "var(--border-color-button-tertiary)",
        "button-tertiary-hover": "var(--border-color-button-tertiary-hover)",
        "button-outline": "var(--border-color-button-outline)",
        "button-outline-hover": "var(--border-color-button-outline-hover)",
        "button-disabled": "var(--border-color-button-disabled)",
        "button-disabled-hover": "var(--border-color-button-disabled-hover)",
        "button-filter": "var(--border-color-button-filter)",
        "button-filter-hover": "var(--border-color-button-filter-hover)",
        "menu-active": "var(--border-color-menu-active)",
        "search-button": "var(--border-color-search-button)",
        "search-input": "var(--border-color-search-input)",
        "search-input-mobile": "var(--border-color-search-input-mobile)",
        pagination: "var(--border-color-pagination)",
        "pagination-hover": "var(--border-color-pagination-hover)",
        checkbox: "var(--border-color-checkbox)",

        invalid: "var(--color-invalid-foreground)",
        valid: "var(--color-valid-foreground)",
        disabled: "var(--color-disabled-foreground)",

        input: "var(--border-color-input)",
        "input-hover": "var(--border-color-input-hover)",
        "input-inverted": "var(--border-color-input-inverted)",
        "input-focused": "var(--border-color-input-focused)",
        listbox: "var(--border-color-search-input)",
        "listbox-option": "var(--border-color-listbox-option)",
        "form-required": "var(--border-color-form-required)",
      }),
      stroke: ({ theme }) => ({
        input: "var(--border-color-input)",
        "input-checked": "var(--text-color-button-primary)",
        "input-focused": "var(--border-color-input-focused)",
        "notification-text": "var(--text-color-legend-error-count)",
        check: "var(--text-color-button-primary)",
        "check-disabled": "var(--color-disabled-background)",
        invalid: "var(--color-invalid-foreground)",
        valid: "var(--color-valid-foreground)",
        disabled: "var(--color-disabled-foreground)",
      }),
      fill: ({ theme }) => ({
        input: "var(--background-color-input)",
        "input-focused": "var(--background-color-input-focused)",
        "input-checked": "var(--background-color-button-primary)",
        notification: "var(--background-color-notification)",
        "notification-text": "var(--text-color-legend-error-count)",
        check: "var(--text-color-button-primary)",
        "fill-checkbox-invalid": "var(--background-color-invalid)",
        invalid: "var(--color-invalid-foreground)",
        valid: "var(--color-valid-foreground)",
        disabled: "var(--color-disabled-foreground)",
      }),
      borderRadius: {
        theme: "var(--border-radius-theme)",
        "3px": "var(--border-radius-3px)",
        "50px": "var(--border-radius-50px)",
        input: "var(--border-radius-input)",
        "textarea-input": "var(--border-radius-textarea-input)",
        "search-input": "var(--border-radius-search-input)",
        "search-button": "var(--border-radius-search-button)",
        pagination: "var(--border-radius-pagination)",
        landing: "var(--border-radius-landing)",
        "form-required": "var(--border-radius-form-required)",
      },
      borderWidth: {
        "form-required": "var(--border-width-form-required)",
        theme: "var(--border-width-theme)",
      },
      opacity: {
        "background-gradient": "var(--opacity-background-gradient)",
      },
      outlineColor: {
        select: "var(--outline-color-select)",
      },
      content: ({ theme }) => ({
        required: "var(--text-content-required)",
      }),
    },
  },
  plugins: ["@tailwindcss/typography", "@tailwindcss/forms"],
};
