{{- if .Values.ingress.enabled }}
  {{- $fullName := include "emx2.fullname" . -}}
  {{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ include "emx2.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: 8088
  {{- end }}
  {{- if .tls }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ .name }}
      {{- end }}
      secretName: {{ .Values.ingress.tlsSecret }}
  {{- end }}
---
{{- end }}
