import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('/apps/central/#/');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByPlaceholder('Enter username').click();
  await page.getByPlaceholder('Enter username').fill('admin');
  await page.getByPlaceholder('Enter username').press('Tab');
  await page.getByPlaceholder('Password').fill('admin');
  await page.getByPlaceholder('Password').press('Enter');
  await page.getByRole('button', { name: '' }).click();
  await page.getByLabel('name').click();
  await page.getByLabel('name').fill('testVisible');
  await page.getByLabel('template').selectOption('PET_STORE');
  await page.getByLabel('true').check();
  await page.getByRole('button', { name: 'Create database' }).click();
  await page.getByRole('link', { name: 'testVisible' }).click();
  await page.getByRole('link', { name: 'Schema' }).click();
  await page.getByText('complete').click();
  await page.getByRole('button', { name: ' ' }).click();
  await page.locator('div:nth-child(2) > .form-group > .input-group > .form-control').click();
  await page.locator('div:nth-child(2) > .form-group > .input-group > .form-control').fill('price >7');
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Tables' }).click();
  await page.getByRole('link', { name: 'Order' }).click();
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('8');
  await page.getByLabel('true').check();
  await expect(page.locator('#Order-edit-modal-complete').getByText('complete')).toBeVisible();
  await expect(page.locator('#Order-edit-modal-complete')).toContainText('true');
  await page.getByRole('button', { name: 'Save Order' }).click();
  await page.getByRole('button', { name: '' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('7');
  await expect(page.locator('#Order-edit-modal-complete').getByText('complete')).toBeHidden();
  await page.getByRole('button', { name: 'Save Order' }).click();
  await page.getByRole('link', { name: 'brand-logo' }).click();
  await page.getByRole('row', { name: '  testVisible' }).getByRole('button').nth(1).click();
  await page.getByRole('button', { name: 'Delete database' }).click();
  await page.getByText('Close').click();
});