plugins {
    id "jacoco"
    id "java"
    id 'java-test-fixtures'
    id "com.diffplug.spotless" version "8.9.0" apply false
    id 'pmd'
}

repositories {
    mavenLocal()
    maven {
        url = 'https://repo.maven.apache.org/maven2'
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-test-fixtures'
    apply plugin: 'jacoco'
    apply plugin: "com.diffplug.spotless"
    apply plugin: "pmd"

    repositories {
        mavenLocal()
        maven {
            url = 'https://repo.maven.apache.org/maven2'
        }
    }

    spotless {
        java {
            googleJavaFormat('1.28.0')
        }
    }

    pmd {
        consoleOutput = true
        toolVersion = "7.26.0"
        ruleSetFiles = files("${project.rootDir}/pmd_ruleset.xml")
        ruleSets = []
    }

    compileJava.dependsOn 'spotlessApply'

    tasks.register('format') {
        dependsOn spotlessApply
        dependsOn pmdMain
        dependsOn pmdTest
    }

    /* default dependencies for all projects*/
    dependencies {
        implementation group: 'org.apache.logging.log4j', name:'log4j-core', version:log4jVersion
        implementation group: 'org.apache.logging.log4j', name:'log4j-slf4j2-impl', version:log4jVersion
        implementation group: 'org.jooq', name:'jooq', version:jooqVersion
        implementation group: 'com.zaxxer', name:'HikariCP', version:hikariCPVersion
        implementation group: 'com.fasterxml.jackson.dataformat', name:'jackson-dataformat-yaml', version:jacksonVersion
        implementation group: 'com.fasterxml.jackson.dataformat', name:'jackson-dataformat-csv', version:jacksonVersion
        implementation group: 'com.fasterxml.jackson.core', name:'jackson-databind', version:jacksonVersion
        implementation group: 'com.fasterxml.jackson.core', name:'jackson-core', version:jacksonVersion
        implementation group: 'com.fasterxml.jackson.core', name:'jackson-annotations', version:jacksonAnnotationsVersion
        implementation group: 'com.graphql-java', name:'graphql-java', version:graphqlVersion
        implementation group: 'com.graphql-java', name:'graphql-java-extended-scalars', version:graphqlScalarsVersion
        implementation group: 'org.pac4j', name:'pac4j-core', version:pac4jVersion
        implementation group: 'org.pac4j', name:'pac4j-oidc', version:pac4jVersion
        implementation group: 'org.pac4j', name:'pac4j-http', version:pac4jVersion
        implementation group: 'io.javalin', name:'javalin', version:javalinVersion
        implementation group: 'org.pac4j', name:'javalin-pac4j', version:javalinPac4jVersion
        implementation group: 'org.javers', name:'javers-core', version:javersVersion
        implementation group: 'com.nimbusds', name:'nimbus-jose-jwt', version:nimbusJoseJwtVersion
        implementation group: 'org.bouncycastle', name:'bcprov-jdk18on', version:bcProvJdk18OnVersion
        implementation group: 'com.schibsted.spt.data', name:'jslt', version:schibstedJsltVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-api', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-jsonld', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-turtle', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-n3', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-trig', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-rdfxml', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-ntriples', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-nquads', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-shacl', version:rdf4jVersion
        implementation group: 'org.eclipse.rdf4j', name:'rdf4j-sail-nativerdf', version:rdf4jVersion

        // also used outside test
        implementation group: 'org.junit.jupiter', name:'junit-jupiter', version:junitVersion
        testRuntimeOnly group: 'org.junit.jupiter', name:'junit-jupiter-engine', version:junitVersion
        testRuntimeOnly group: 'org.junit.jupiter', name:'junit-platform-launcher', version:junitVersion
        testImplementation group: 'org.mockito', name:'mockito-core', version:mockitoVersion
        // allows to set environment variables in test
        testImplementation group: 'com.github.stefanbirkner', name:'system-lambda', version:systemLambdaVersion
        // Allow generic test fixtures to be available everywhere
        testImplementation testFixtures(project(':backend:molgenis-emx2'))

        // test fixture dependencies
        testFixturesImplementation group: 'org.junit.jupiter', name:'junit-jupiter', version:junitVersion
        testFixturesImplementation group: 'org.junit.jupiter', name:'junit-jupiter-engine', version:junitVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-api', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-jsonld', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-turtle', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-n3', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-trig', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-rdfxml', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-ntriples', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-rio-nquads', version:rdf4jVersion
        testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-shacl', version:rdf4jVersion
        testFixturesImplementation group: 'org.apache.commons', name:'commons-collections4', version:commonsCollectionsVersion
    }

    jacoco {
        toolVersion = "0.8.15"
    }
    jacocoTestReport {
        reports {
            xml.required = true
            csv.required = false
            html.required = false
        }
    }

    java {
        targetCompatibility = rootProject.ext.javaVersion
        sourceCompatibility = rootProject.ext.javaVersion
    }

    jar {
        reproducibleFileOrder = true
        manifest {
            attributes(
                    'Specification-Version': project.version.toString(),
                    'Implementation-Version': getGitHash(),
                    'Created-By': "Gradle ${gradle.gradleVersion}",
                    'Build-Jdk': "${System.properties['java.version']} (${System.properties['java.vendor']} ${System.properties['java.vm.version']})",
                    'Build-OS': "${System.properties['os.name']} ${System.properties['os.arch']} ${System.properties['os.version']}"
            )
        }
    }

    test {
        jvmArgs("--add-opens=java.base/java.util=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "-XX:+EnableDynamicAgentLoading")
        useJUnitPlatform()
        testLogging {
            events "passed", "skipped", "failed" //, "standardOut", "standardError"

            showExceptions = true
            exceptionFormat = "full"
            showCauses = true
            showStackTraces = true

            showStandardStreams = false
        }
    }

    tasks.withType(Test).configureEach { rootProject.ext.forwardDotenvAsEnvironment(it) }
    tasks.withType(JavaExec).configureEach { rootProject.ext.forwardDotenvAsSystemProperties(it) }

    test.dependsOn ":backend:molgenis-emx2-sql:initDatabase"

    tasks.register('testFast', Test) {
        jvmArgs("--add-opens=java.base/java.util=ALL-UNNAMED")
        useJUnitPlatform {
            excludeTags "slow"
        }
        failFast = true
        testLogging {
            events "passed", "skipped", "failed" //, "standardOut", "standardError"

            showExceptions = true
            exceptionFormat = "full"
            showCauses = true
            showStackTraces = true

            showStandardStreams = false
        }
    }
    tasks.register('testWindows', Test) {
        jvmArgs("--add-opens=java.base/java.util=ALL-UNNAMED")
        useJUnitPlatform {
            excludeTags "windowsFail"
        }
        failFast = true
        testLogging {
            events "passed", "skipped", "failed" //, "standardOut", "standardError"

            showExceptions = true
            exceptionFormat = "full"
            showCauses = true
            showStackTraces = true

            showStandardStreams = false
        }
    }
}

/* have webapi tests run after all other modules (starts web service, needs exclusive DB access) */
project(":backend:molgenis-emx2-webapi").test.dependsOn subprojects.findAll {
    it != project(":backend:molgenis-emx2-webapi") && it != project(":backend:molgenis-emx2-nonparallel-tests")
}.collect { ":backend:${it.name}:test" }

/* have the non-parallel test package run last*/
project(":backend:molgenis-emx2-nonparallel-tests").test.dependsOn subprojects.findAll { it != project(":backend:molgenis-emx2-nonparallel-tests") }.collect { ":backend:${it.name}:test" }

/* generate java test coverage report*/
test.dependsOn subprojects.test
tasks.register('jacocoMergedReport', JacocoReport) {
    dependsOn test
    additionalSourceDirs.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
    sourceDirectories.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
    classDirectories.setFrom files(subprojects.sourceSets.main.output)
    executionData.setFrom project.fileTree(dir: '.', include: '**/build/jacoco/test.exec')
    reports {
        xml.required = true
        csv.required = false
        html.required = false
    }
}
