plugins {
    id "jacoco"
    id "java"
    id 'java-test-fixtures'
    alias(libs.plugins.diffplug.spotless) apply false
    id 'pmd'
}

repositories {
    mavenLocal()
    maven {
        url = 'https://repo.maven.apache.org/maven2'
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-test-fixtures'
    apply plugin: 'jacoco'
    apply plugin: "com.diffplug.spotless"
    apply plugin: "pmd"

    repositories {
        mavenLocal()
        maven {
            url = 'https://repo.maven.apache.org/maven2'
        }
    }

    spotless {
        java {
            googleJavaFormat(libs.versions.g.googleJavaFormat)
        }
    }

    pmd {
        consoleOutput = true
        toolVersion = libs.versions.g.pmd
        ruleSetFiles = files("${project.rootDir}/pmd_ruleset.xml")
        ruleSets = []
    }

    compileJava.dependsOn 'spotlessApply'

    tasks.register('format') {
        dependsOn spotlessApply
        dependsOn pmdMain
        dependsOn pmdTest
    }

    /* default dependencies for all projects*/
    dependencies {
        implementation libs.bundles.log4j
        implementation libs.jooq
        implementation libs.hikaricp
        implementation libs.bundles.jackson
        implementation libs.bundles.graphql
        implementation libs.bundles.pac4j
        implementation libs.bundles.javalin
        implementation libs.javers.core
        implementation libs.nimbus.jose.jwt
        implementation libs.bcprov.jdk18on
        implementation libs.jslt
        implementation libs.bundles.rdf4j.rio
        implementation libs.rdf4j.shacl
        implementation libs.rdf4j.sail.nativerdf

        // also used outside test
        implementation libs.junit.jupiter
        testRuntimeOnly libs.junit.jupiter.engine
        testRuntimeOnly libs.junit.platform.launcher
        testImplementation libs.mockito.core
        // allows to set environment variables in test
        testImplementation libs.system.lambda
        // Allow generic test fixtures to be available everywhere
        testImplementation testFixtures(project(':backend:molgenis-emx2'))

        // test fixture dependencies
        testFixturesImplementation libs.junit.jupiter
        testFixturesImplementation libs.junit.jupiter.engine
        testFixturesImplementation libs.bundles.rdf4j.rio
        testFixturesImplementation libs.rdf4j.shacl
        testFixturesImplementation libs.commons.collections4
    }

    jacoco {
        toolVersion = libs.versions.g.jacoco
    }
    jacocoTestReport {
        reports {
            xml.required = true
            csv.required = false
            html.required = false
        }
    }

    java {
        targetCompatibility = rootProject.ext.javaVersion
        sourceCompatibility = rootProject.ext.javaVersion
    }

    jar {
        reproducibleFileOrder = true
        manifest {
            attributes(
                    'Specification-Version': project.version.toString(),
                    'Implementation-Version': getGitHash(),
                    'Created-By': "Gradle ${gradle.gradleVersion}",
                    'Build-Jdk': "${System.properties['java.version']} (${System.properties['java.vendor']} ${System.properties['java.vm.version']})",
                    'Build-OS': "${System.properties['os.name']} ${System.properties['os.arch']} ${System.properties['os.version']}"
            )
        }
    }

    test {
        jvmArgs("--add-opens=java.base/java.util=ALL-UNNAMED", "--add-opens=java.base/java.lang=ALL-UNNAMED", "-XX:+EnableDynamicAgentLoading")
        useJUnitPlatform()
        testLogging {
            events "passed", "skipped", "failed" //, "standardOut", "standardError"

            showExceptions = true
            exceptionFormat = "full"
            showCauses = true
            showStackTraces = true

            showStandardStreams = false
        }
    }

    tasks.withType(Test).configureEach { rootProject.ext.forwardDotenvAsEnvironment(it) }
    tasks.withType(JavaExec).configureEach { rootProject.ext.forwardDotenvAsSystemProperties(it) }

    test.dependsOn ":backend:molgenis-emx2-sql:initDatabase"

    tasks.register('testFast', Test) {
        jvmArgs("--add-opens=java.base/java.util=ALL-UNNAMED")
        useJUnitPlatform {
            excludeTags "slow"
        }
        failFast = true
        testLogging {
            events "passed", "skipped", "failed" //, "standardOut", "standardError"

            showExceptions = true
            exceptionFormat = "full"
            showCauses = true
            showStackTraces = true

            showStandardStreams = false
        }
    }
    tasks.register('testWindows', Test) {
        jvmArgs("--add-opens=java.base/java.util=ALL-UNNAMED")
        useJUnitPlatform {
            excludeTags "windowsFail"
        }
        failFast = true
        testLogging {
            events "passed", "skipped", "failed" //, "standardOut", "standardError"

            showExceptions = true
            exceptionFormat = "full"
            showCauses = true
            showStackTraces = true

            showStandardStreams = false
        }
    }
}

/* have webapi tests run after all other modules (starts web service, needs exclusive DB access) */
project(":backend:molgenis-emx2-webapi").test.dependsOn subprojects.findAll {
    it != project(":backend:molgenis-emx2-webapi") && it != project(":backend:molgenis-emx2-nonparallel-tests")
}.collect { ":backend:${it.name}:test" }

/* have the non-parallel test package run last*/
project(":backend:molgenis-emx2-nonparallel-tests").test.dependsOn subprojects.findAll { it != project(":backend:molgenis-emx2-nonparallel-tests") }.collect { ":backend:${it.name}:test" }

/* generate java test coverage report*/
test.dependsOn subprojects.test
tasks.register('jacocoMergedReport', JacocoReport) {
    dependsOn test
    additionalSourceDirs.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
    sourceDirectories.setFrom files(subprojects.sourceSets.main.allSource.srcDirs)
    classDirectories.setFrom files(subprojects.sourceSets.main.output)
    executionData.setFrom project.fileTree(dir: '.', include: '**/build/jacoco/test.exec')
    reports {
        xml.required = true
        csv.required = false
        html.required = false
    }
}
