dependencies {
    implementation project(':backend:molgenis-emx2')
    implementation group: 'javax.mail', name:'mail', version:javaxMailVersion
    testImplementation group: 'org.junit.jupiter', name:'junit-jupiter-api', version:junitVersion
    testRuntimeOnly group: 'org.junit.jupiter', name:'junit-jupiter-engine', version:junitVersion
}
