query Variables($filter: VariablesFilter) {
  Variables_agg(filter: $filter) {
    count
  }
  Variables(limit: 20, filter: $filter) {
    name
    label
    description
    format {
      name
    }
    unit {
      name
    }
    release {
      resource {
        mg_tableclass
        acronym
      }
      version
    }
  }
}
