query VariableMappings($filter: VariableMappingsFilter) {
  VariableMappings(limit: 200, filter: $filter) {
    fromRelease {
      resource {
        pid
      }
      version
    }
    toVariable {
      table {
        release {
          resource {
            pid
          }
          version
        }
        name
      }
      name
    }
    match {
      name
    }
  }
}
