query VariableMappings($filter: VariableMappingsFilter) {
  VariableMappings(limit: 200, filter: $filter) {
    fromTable {
      release {
        resource {
          pid
        }
        version
      }
      name
    }
    toVariable {
      table {
        release {
          resource {
            pid
          }
          version
        }
        name
      }
      name
    }
    match {
      name
    }
  }
}
