PREFIX afr: <http://purl.allotrope.org/ontologies/result#>
PREFIX afrl: <http://purl.allotrope.org/ontologies/role#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcatap: <http://data.europa.eu/r5r/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX edam: <http://edamontology.org/>
PREFIX efo: <http://www.ebi.ac.uk/efo/>
PREFIX ejp: <https://w3id.org/ejp-rd/vocabulary#>
PREFIX ensembl: <http://ensembl.org/glossary/>
PREFIX fdp-o: <https://w3id.org/fdp/fdp-o#>
PREFIX fg: <https://w3id.org/fair-genomes/resource/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX healthdcatap: <http://healthdataportal.eu/ns/health#>
PREFIX hl7: <http://purl.bioontology.org/ontology/HL7/>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
PREFIX lnc: <http://purl.bioontology.org/ontology/LNC/>
PREFIX mesh: <http://purl.bioontology.org/ontology/MESH/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX ordo: <http://www.orpha.net/ORDO/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX snomedct: <http://purl.bioontology.org/ontology/SNOMEDCT/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
    ?rdf_type ?fdp_endpoint ?ldp_membership_relation ?id ?pid ?name ?local_name ?acronym ?website ?description ?start_year ?end_year ?conforms_to ?has_member_relation ?issued ?modified ?design_description ?data_collection_description ?reason_sustained ?data_resources ?number_of_participants ?underlying_population ?countries ?continents ?regions ?age_min ?age_max ?publisher ?creator ?contact_point ?child_networks ?access_rights ?release_type ?provenance_statement ?theme ?applicable_legislation
    (GROUP_CONCAT(?keyword; separator=",") AS ?keywords)
WHERE {
    ?Resources dcterms:title ?id ;
        dcterms:title ?name .
    OPTIONAL { ?Resources rdf:type ?rdf_type . }
    OPTIONAL {
        ?Resources ldp:membershipResource ?fdp_endpoint .
        OPTIONAL { ?fdp_endpoint schema:identifier ?Endpoint_fdp_endpoint_Endpoint_id0 . }
        OPTIONAL { ?fdp_endpoint dcterms:identifier ?Endpoint_fdp_endpoint_Endpoint_id1 . }
        BIND( COALESCE( ?Endpoint_fdp_endpoint_Endpoint_id0, ?Endpoint_fdp_endpoint_Endpoint_id1 ) AS ?Endpoint_fdp_endpoint_Endpoint_id )
    }
    OPTIONAL { ?Resources ldp:hasMemberRelation ?ldp_membership_relation . }
    OPTIONAL { ?Resources dcterms:identifier ?pid . }
    OPTIONAL { ?Resources rdfs:label ?local_name . }
    OPTIONAL { ?Resources dcterms:alternative ?acronym . }
    OPTIONAL { ?Resources dcat:landingPage ?website . }
    OPTIONAL { ?Resources dcterms:description ?description . }
    OPTIONAL { ?Resources dcat:keyword ?keyword . }
    OPTIONAL { ?Resources dcat:startDate ?start_year . }
    OPTIONAL { ?Resources dcat:endDate ?end_year . }
    OPTIONAL { ?Resources dcterms:conformsTo ?conforms_to . }
    OPTIONAL { ?Resources ldp:hasMemberRelation ?has_member_relation . }
    OPTIONAL { ?Resources dcterms:issued ?issued . }
    OPTIONAL { ?Resources dcterms:modified ?modified . }
    OPTIONAL { ?Resources dcterms:provenance ?design_description . }
    OPTIONAL { ?Resources dcterms:provenance ?data_collection_description . }
    OPTIONAL { ?Resources dcterms:provenance ?reason_sustained . }
    OPTIONAL {
        ?Resources dcat:dataset ?data_resources .
        OPTIONAL { ?data_resources dcterms:title ?Resources_data_resources_Resources_id0 . }
        OPTIONAL { ?data_resources dcterms:alternative ?Resources_data_resources_Resources_id1 . }
        BIND( COALESCE( ?Resources_data_resources_Resources_id0, ?Resources_data_resources_Resources_id1 ) AS ?Resources_data_resources_Resources_id )
    }
    OPTIONAL { ?Resources healthdcatap:numberOfUniqueIndividuals ?number_of_participants . }
    OPTIONAL { ?Resources healthdcatap:populationCoverage ?underlying_population . }
    OPTIONAL { ?Resources dcterms:spatial ?countries . }
    OPTIONAL { ?Resources dcterms:spatial ?continents . }
    OPTIONAL { ?Resources dcterms:spatial ?regions . }
    OPTIONAL { ?Resources healthdcatap:minimumTypicalAge ?age_min . }
    OPTIONAL { ?Resources healthdcatap:maximumTypicalAge ?age_max . }
    OPTIONAL {
        ?Resources dcterms:publisher ?publisher .
        OPTIONAL { ?publisher dcterms:title ?Resources_publisher_Resources_id0 . }
        OPTIONAL { ?publisher dcterms:alternative ?Resources_publisher_Resources_id1 . }
        BIND( COALESCE( ?Resources_publisher_Resources_id0, ?Resources_publisher_Resources_id1 ) AS ?Resources_publisher_Resources_id )
    }

    OPTIONAL {
        ?Resources dcterms:creator ?creator .
        OPTIONAL { ?creator dcterms:title ?Resources_creator_Resources_id0 . }
        OPTIONAL { ?creator dcterms:alternative ?Resources_creator_Resources_id1 . }
        BIND( COALESCE( ?Resources_creator_Resources_id0, ?Resources_creator_Resources_id1 ) AS ?Resources_creator_Resources_id )
    }

    OPTIONAL {
         ?Resources dcat:contactPoint ?contact_point .
        OPTIONAL { ?contact_point dcterms:title ?Resources_contact_point_Resources_id0 . }
        OPTIONAL { ?contact_point dcterms:alternative ?Resources_contact_point_Resources_id1 . }
        BIND( COALESCE( ?Resources_contact_point_Resources_id0, ?Resources_contact_point_Resources_id1 ) AS ?Resources_contact_point_Resources_id )
    }

    OPTIONAL {
        ?Resources dcat:catalog ?child_networks .
        OPTIONAL { ?child_networks dcterms:title ?Resources_child_networks_Resources_id0 . }
        OPTIONAL { ?child_networks dcterms:alternative ?Resources_child_networks_Resources_id1 . }
        BIND( COALESCE( ?Resources_child_networks_Resources_id0, ?Resources_child_networks_Resources_id1 ) AS ?Resources_child_networks_Resources_id )
    }

    OPTIONAL { ?Resources dcterms:accessRights ?access_rights . }
    OPTIONAL { ?Resources dcterms:accrualPeriodicity ?release_type . }
    OPTIONAL { ?Resources dcterms:provenance ?provenance_statement . }
    OPTIONAL { ?Resources dcat:theme ?theme . }
    OPTIONAL { ?Resources dcatap:applicableLegislation ?applicable_legislation . }
}
GROUP BY
?rdf_type ?fdp_endpoint ?ldp_membership_relation ?id ?pid ?name ?local_name ?acronym ?website ?description ?start_year ?end_year ?conforms_to ?has_member_relation ?issued ?modified ?design_description ?data_collection_description ?reason_sustained ?data_resources ?number_of_participants ?underlying_population ?countries ?continents ?regions ?age_min ?age_max ?publisher ?creator ?contact_point ?child_networks ?access_rights ?release_type ?provenance_statement ?theme ?applicable_legislation