<template>
  <header>
    <div
      :class="headerClassNames"
      :style="imageSrc ? `background-image: url(${imageSrc})` : ''"
    >
      <div class="header-content" v-if="title || subtitle">
        <h1 class="header-title">{{ title }}</h1>
        <h2 class="header-subtitle">{{ subtitle }}</h2>
      </div>
      <div
        class="background-image-filter"
        v-if="imageSrc"
        aria-hidden="true"
      ></div>
    </div>
    <slot></slot>
  </header>
</template>

<script>
const heightOptions = ["small", "medium", "large", "full"];
const yPositions = ["top", "center", "bottom"];
const xPositions = ["left", "center", "right"];

// Create a header element for the page that displays a title, subtitle, and images. You may specify the position of the title using the `titlePosition*` attributes. A background image may also be set using the `imageSrc` property.
// @group LAYOUTS
export default {
  props: {
    // a title for the page
    title: {
      type: String,
      required: false,
    },
    // a subtitle for the page
    subtitle: {
      type: String,
      required: false,
    },
    // the path of an image generated by Vue
    imageSrc: {
      type: String,
    },
    // specify the height of the component
    height: {
      // `'small' / 'medium' / 'large' / 'full'`
      type: String,
      // `small`
      default: "small",
      validator: (value) => {
        return heightOptions.includes(value);
      },
    },
    // the horizontal position of the title and subtitle
    titlePositionX: {
      // `'left' / 'center' / 'right'`
      type: String,
      // `left`
      default: "left",
      validator: (value) => {
        return xPositions.includes(value);
      },
    },
    // the vertical position of the title and subtitle
    titlePositionY: {
      // `'top' / 'center' / 'bottom'`
      type: String,
      // `center`
      default: "center",
      validator: (value) => {
        return yPositions.includes(value);
      },
    },
    // set the left and right padding of the header element
    horizontalPadding: {
      // `0:5`
      type: Number,
      // `1`
      default: 1,
      validator: (value) => {
        return value >= 0 && value <= 5;
      },
    },
    // set the top and bottom padding of the header element
    verticalPadding: {
      // `0:5`
      type: Number,
      // `1`
      default: 1,
      validator: (value) => {
        return value >= 0 && value <= 5;
      },
    },
    // move title and subtitle to below the image
    moveContentBelowImage: {
      type: Boolean,
      // `false`
      default: false,
    },
  },
  computed: {
    headerClassNames() {
      const css = [
        "page-header",
        `height-${this.height}`,
        `padding-h-${this.horizontalPadding}`,
        `padding-v-${this.verticalPadding}`,
        `text-position-x-${this.titlePositionX}`,
        `text-position-y-${this.titlePositionY}`,
      ];

      if (this.imageSrc) {
        css.push("header-image-background");
      }
      return css.join(" ");
    },
  },
};
</script>

<style lang="scss">
.page-header {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;

  .header-content {
    width: 90%;
    margin: 0 auto;
    z-index: 1;

    h1,
    h2 {
      margin: 0;
      line-height: 1.3;
      color: currentColor;
    }

    .header-title {
      font-size: 13pt;
      text-transform: uppercase;
      letter-spacing: 4px;
      font-weight: bold;
    }

    .header-subtitle {
      font-size: 32pt;
      font-weight: 200;
    }
  }

  &.header-image-background {
    background-size: cover;
    background-position: 0 44%;

    .header-content {
      .header-title {
        color: $gray-050;
      }
      .header-subtitle {
        color: $gray-050;
      }
    }

    .background-image-filter {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: $gray-transparent-500;
    }
  }
}
</style>
