/** abstract component that is used as superclass, will not be shown in style
guide */

<script>
import _formGroup from "./_formGroup.vue";

const uuidv4 = require("uuid/v4");

export default {
  components: {
    "form-group": _formGroup,
  },
  props: {
    /**  value */
    value: { type: [String, Number, Object, Array, Boolean], default: null },
    /** wether to enable in place editing */
    inplace: Boolean,
    /** value to be shown as placeholder in the input (if possible) */
    placeholder: String,
    /** label to be shown above the input */
    label: String,
    /** optional description string shown below input */
    description: String,
    /** whether input must be required (does not validate, but show option to clear input) */
    required: {
      type: Boolean,
      default: false,
    },
    /** whether input is readonly (default: false) */
    readonly: {
      type: Boolean,
      default: false,
    },
    /** message when in error state */
    errorMessage: null,
    /** whether this is a list of values*/
    list: {
      type: Boolean,
      default: false,
    },
    /** whether to show clear buttons */
    clear: {
      type: Boolean,
      default: true,
    },
    /** parse function, such as parseInt to type value*/
    parser: Function,
  },
  data() {
    return {
      /** unique identifier, autogenerated */
      id: uuidv4(),
      /** whether list input should show empty input */
      showNewItem: false,
      /** whether input has focus */
      focus: false,
    };
  },
  computed: {
    valueArray() {
      let result = this.value;
      if (!result) result = null;
      if (!Array.isArray(result)) {
        result = [result];
      }
      result = this.removeNulls(result);
      if (result.length == 0 || (this.list && this.showNewItem)) {
        result.push(null);
      }
      return result;
    },
  },
  // generate automatic id
  mounted() {
    this.id = Math.random().toString(36).substring(7);
  },
  methods: {
    removeNulls(arr) {
      return arr.filter((v) => v === 0 || v);
    },
    //emit update with new item on list
    emitValue(event, idx) {
      let value = event ? (event.target ? event.target.value : event) : null;
      let result;
      if (this.list) {
        result = this.valueArray;
        //update value
        result[idx] = value;
        //update newItem if needed
        if (this.showNewItem && result[result.length - 1] != null) {
          this.showNewItem = false;
        }
        //remove nulls
        result = this.removeNulls(result);
      } else {
        result = value;
      }
      this.$emit("input", result);
    },
    toggleFocus() {
      this.focus = !this.focus;
    },
    addRow() {
      this.showNewItem = true;
    },
    clearValue(idx) {
      let result = this.valueArray;
      if (this.list) {
        result.splice(idx, 1);
      } else {
        result = null;
      }
      this.$emit("input", result);
    },
    showPlus(idx) {
      //always on last line
      return (
        this.list &&
        !this.showNewItem &&
        idx == this.valueArray.length - 1 &&
        this.valueArray[idx] != null
      );
    },
    //always show on empty lines in list view
    showClear() {
      return this.clear && !this.readonly;
    },
    showMinus(idx) {
      return this.list && !this.showPlus(idx);
    },
  },
  directives: {
    focus: {
      inserted(el, binding) {
        if (binding.value) {
          el.focus();
        }
      },
    },
  },
};
</script>
