/** abstract component that is used as superclass, will not be shown in style
guide */

<script>
import _formGroup from "./_formGroup.vue";

const uuidv4 = require("uuid/v4");

export default {
  components: {
    "form-group": _formGroup,
  },
  props: {
    /**  value */
    value: [String, Number, Object, Array, Boolean],
    /** wether to enable in place editing */
    inplace: Boolean,
    /** value to be shown as placeholder in the input (if possible) */
    placeholder: String,
    /** label to be shown above the input */
    label: String,
    /** optional help string shown below input */
    help: String,
    /** whether input must be required (does not validate, but show option to clear input) */
    required: {
      type: Boolean,
      default: false,
    },
    /** whether input is readonly (default: false) */
    readonly: {
      type: Boolean,
      default: false,
    },
    /** message when in error state */
    error: null,
    /** whether this is a list of values*/
    list: {
      type: Boolean,
      default: false,
    },
    /** whether to show clear buttons */
    clear: {
      type: Boolean,
      default: true,
    },
    /** parse function, such as parseInt to type value*/
    parser: Function,
  },
  data() {
    return {
      /** unique identifier, autogenerated */
      id: uuidv4(),
      /** internal value to differ between list and non-list values*/
      arrayValue: [],
      /** whether input has focus */
      focus: false,
      /** pretty value, updated when emitValue */
      prettyValue: null,
    };
  },
  watch: {
    value() {
      //why doesn't have javascript proper equals!!!
      if (JSON.stringify(this.value) != JSON.stringify(this.getValue())) {
        this.init();
      }
    },
  },
  // generate automatic id
  mounted() {
    this.id = Math.random().toString(36).substring(7);
  },
  created() {
    this.init();
  },
  methods: {
    init() {
      if (this.list) {
        if (this.value && Array.isArray(this.value)) {
          this.arrayValue = this.value;
        } else if (this.value) {
          this.arrayValue = [this.value];
        } else {
          this.arrayValue = [null];
        }
      } else {
        this.arrayValue[0] = this.value;
      }
      if (this.arrayValue == null || this.arrayValue.length == 0) {
        this.arrayValue = [];
      }
      //note, initially we used 'computed' but that doesn't always update imediately
      this.prettyValue = this.getValue();
      console.log(
        JSON.stringify(this.value) + " " + JSON.stringify(this.prettyValue)
      );
    },
    getValue() {
      //list type
      var value;
      if (this.list) {
        if (Array.isArray(this.arrayValue)) {
          value = this.arrayValue.map((v) =>
            v === undefined || (v && v.length === 0) || !String(v).trim()
              ? null
              : v
          );
        } else if (this.arrayValue) {
          value = [this.arrayValue];
        } else {
          value = [];
        }
        value = value.filter((el) => el != undefined);
        if (this.parser != null) {
          value = value.map((v) => this.parser(v));
        }
        //singular value
      } else {
        value = this.arrayValue[0];
        //console.log("value: " + this.value);
        if (
          value === undefined ||
          (value && value.length === 0) ||
          !String(value).trim()
        ) {
          value = null;
        }
        if (this.parser != null) {
          value = this.parser(value);
        }
      }
      return value;
    },
    toggleFocus() {
      this.focus = !this.focus;
    },
    emitValue() {
      this.prettyValue = this.getValue();
      this.$emit("input", this.prettyValue);
    },
    addRow() {
      this.arrayValue.push();
    },
    clearValue(idx) {
      if (this.arrayValue.length > 1) {
        this.arrayValue.splice(idx, 1);
      } else {
        if (this.list) {
          this.arrayValue = [[]];
        } else {
          this.arrayValue = [];
        }
      }
      this.emitValue();
    },
    showPlus(idx) {
      //always on last line
      return this.list && idx == this.arrayValue.length - 1;
    },
    //always show on empty lines in list view
    showClear() {
      return this.clear;
    },
    showMinus(idx) {
      return this.list && idx != this.arrayValue.length - 1;
    },
  },
  directives: {
    focus: {
      inserted(el, binding) {
        if (binding.value) {
          el.focus();
        }
      },
    },
  },
};
</script>
