name: Feature request
description: Suggest an enhancement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: A clear and concise description of what feature is currently missing. What issues are you currently running into?
      placeholder: "Currently I'm missing a specialized column type for storing email addresses. While I could use a String, I want these to also correctly use the 'mailto:' hyperlink in the table view."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.
      placeholder: |
        A new ColumnType for email addresses with propper support for related functionalities:
        - Clickable links with 'mailto:' in the table view
        - <mailto:my@example.com> in RDF API
        - etc.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: "Using different ColumnTypes. While it is possible, for example in the RDF API this could lead to invalidly formatted output."
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: "Reason for this request is we're trying to use EMX2 RDF API and we're missing this data being outputted as we would need."