ALTER TABLE "MOLGENIS"."column_metadata" ADD COLUMN IF NOT EXISTS role VARCHAR;
ALTER TABLE "MOLGENIS"."column_metadata" ADD COLUMN IF NOT EXISTS display VARCHAR;
ALTER TABLE "MOLGENIS"."table_metadata" ADD COLUMN IF NOT EXISTS table_role VARCHAR;
