IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'version_metadata' AND SCHEMA_NAME = 'MOLGENIS')
BEGIN
TRUNCATE "MOLGENIS"."version_metadata";
ALTER TABLE "MOLGENIS"."version_metadata" DROP COLUMN "version";
ALTER TABLE "MOLGENIS"."version_metadata"
    ADD COLUMN "version" INTEGER NOT NULL;
END IF;