<template>
  <div :class="classNames" :style="setStyle">
    <div class="card-content">
      <!-- Card content -->
      <slot></slot>
    </div>
    <div class="card-background-filter" v-if="imageSrc" />
  </div>
</template>

<script>
// Create a card component for rendering links to internal or external pages.
// This component is primarily used for creating a "quick links" section
// on the home page. You can also set a background image using the `imageSrc`
// property.
export default {
  props: {
    // the path to the image generated by Vue
    imageSrc: {
      type: String,
    },
    // specify the left and right padding of the default slot
    horizontalPadding: {
      // `0:5`
      type: Number,
      // `3`
      default: 3,
      validator: (value) => {
        return value >= 0 && value <= 5;
      },
    },
    // specify the top and bottom padding of the default slote
    verticalPadding: {
      // `0:5`
      type: Number,
      // `3`
      default: 3,
      validator: (value) => {
        return value >= 0 && value <= 5;
      },
    },
  },
  computed: {
    classNames() {
      const base = "link-card";
      const image = this.imageSrc ? "card-image-background" : "";
      const hPadding = `padding-h-${this.horizontalPadding}`;
      const vPadding = `padding-v-${this.verticalPadding}`;
      return [base, image, hPadding, vPadding].join(" ");
    },
    setStyle() {
      return this.imageSrc ? `background-image: url(${this.imageSrc})` : "";
    },
  },
};
</script>

<style lang="scss">
.link-card {
  display: flex;
  justify-content: center;
  align-items: center;
  position: relative;
  background-color: $gray-900;
  $border-radius: 8pt;
  border-radius: $border-radius;

  .card-content {
    z-index: 1;

    a {
      @include textTransform(bold);
      color: $gray-050;
      font-size: 1.1rem;
    }
  }

  &.card-image-background {
    background-size: cover;
    background-position: 0 44%;

    .card-background-filter {
      position: absolute;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: $gray-transparent-500;
      border-radius: $border-radius;
    }
  }
}
</style>
