/** abstract component that is used as superclass, will not be shown in style
guide */

<script>
import _formGroup from './_formGroup.vue'

export default {
  components: {
    'form-group': _formGroup
  },
  props: {
    /** value to be shown as placeholder in the input (if possible) */
    placeholder: String,
    /** label to be shown above the input */
    label: String,
    /** optional help string shown below input */
    help: String,
    /** whether input can nullable (does not validate, but show option to clear input) */
    nullable: {
      type: Boolean,
      default: false
    },
    /** wheter input is readonly (default: false) */
    readonly: {
      type: Boolean,
      default: false
    },
    /** message when in error state */
    error: null,
    /** default value */
    defaultValue: null,
    /** whether this is a list of values*/
    list: {
      type: Boolean,
      default: false
    },
    /** whether to show clear buttons */
    clear: {
      type: Boolean,
      default: true
    }
  },
  data() {
    return {
      /** unique identifier, autogenerated */
      id: null,
      /** internal value to differ between list and non-list values*/
      arrayValue: [],
      /** external visible value you can v-model on */
      value: null
    }
  },
  watch: {
    arrayValue() {
      this.emitValue()
    }
  },
  // generate automatic id
  mounted() {
    this.id = Math.random()
      .toString(36)
      .substring(7)
  },
  created() {
    if (this.list) {
      if (this.defaultValue) {
        this.arrayValue = this.defaultValue
      }
    } else {
      this.arrayValue[0] = this.defaultValue
    }
    if (this.arrayValue === null || this.arrayValue.length == 0) {
      this.arrayValue = [null]
    }
    this.emitValue()
  },
  methods: {
    emitValue() {
      if (this.list) {
        this.value = this.arrayValue.map(v =>
          v === null || v.trim() === '' ? null : v
        )
        this.value = this.value.filter(el => el !== null)
      } else {
        this.value = this.arrayValue[0]
        if (this.value === null || this.value.trim() === '') {
          this.value = null
        }
      }
      this.$emit('input', this.value)
    },
    addRow() {
      this.arrayValue.push(null)
    },
    clearValue(idx) {
      if (this.arrayValue.length > 1) {
        this.arrayValue.splice(idx, 1)
      } else {
        this.arrayValue = [null]
      }
    },
    showPlus(idx) {
      return (
        this.list &&
        !this.readonly &&
        this.arrayValue[idx] !== null &&
        this.arrayValue[idx] !== '' &&
        idx === this.arrayValue.length - 1
      )
    },
    showClear(idx) {
      return (
        !this.readonly &&
        this.clear &&
        this.arrayValue !== null &&
        this.arrayValue[idx] !== null
      )
    }
  }
}
</script>
