/** abstract component that is used as superclass, will not be shown in style
guide */

<script>
import _formGroup from "./_formGroup.vue";

export default {
  components: {
    "form-group": _formGroup
  },
  props: {
    /** value to be shown as placeholder in the input (if possible) */
    placeholder: String,
    /** label to be shown above the input */
    label: String,
    /** optional help string shown below input */
    help: String,
    /** whether input can nullable (does not validate, but show option to clear input) */
    nullable: {
      type: Boolean,
      default: false
    },
    /** whether input is readonly (default: false) */
    readonly: {
      type: Boolean,
      default: false
    },
    /** message when in error state */
    error: null,
    /** default value */
    defaultValue: null,
    /** whether this is a list of values*/
    list: {
      type: Boolean,
      default: false
    },
    /** whether to show clear buttons */
    clear: {
      type: Boolean,
      default: true
    },
    /** parse function, such as parseInt to type value*/
    parser: Function
  },
  data() {
    return {
      /** unique identifier, autogenerated */
      id: null,
      /** internal value to differ between list and non-list values*/
      arrayValue: [],
      /** external visible value you can v-model on */
      value: null
    };
  },
  watch: {
    arrayValue() {
      this.emitValue();
    }
  },
  // generate automatic id
  mounted() {
    this.id = Math.random()
      .toString(36)
      .substring(7);
  },
  created() {
    if (this.list) {
      if (this.defaultValue) {
        this.arrayValue = this.defaultValue;
      }
    } else {
      this.arrayValue[0] = this.defaultValue;
    }
    if (this.arrayValue === null || this.arrayValue.length == 0) {
      this.arrayValue = [null];
    }
    this.emitValue();
  },
  methods: {
    emitValue() {
      //list type
      if (this.list) {
        //else continue
        this.value = this.arrayValue.map(v =>
          !v || v.length === 0 || !String(v).trim() ? null : v
        );
        this.value = this.value.filter(el => el != undefined);
        if (this.parser != null) {
          this.value = this.value.map(v => this.parser(v));
        }
        //singular value
      } else {
        this.value = this.arrayValue[0];
        if (
          !this.value ||
          this.value.length === 0 ||
          !String(this.value).trim()
        ) {
          this.value = null;
        }
        if (this.parser != null) {
          this.value = this.parser(this.value);
        }
      }
      this.$emit("input", this.value);
    },
    addRow() {
      this.arrayValue.push(null);
    },
    clearValue(idx) {
      if (this.arrayValue.length > 1) {
        this.arrayValue.splice(idx, 1);
      } else {
        if (this.list) {
          this.arrayValue = [[null]];
        } else {
          this.arrayValue = [null];
        }
      }
    },
    showPlus(idx) {
      return (
        this.list &&
        !this.readonly &&
        this.arrayValue[idx] !== null &&
        this.arrayValue[idx] !== "" &&
        idx === this.arrayValue.length - 1
      );
    },
    showClear(idx) {
      return (
        !this.readonly &&
        this.clear &&
        this.arrayValue !== null &&
        this.arrayValue[idx] !== null
      );
    }
  }
};
</script>
