/** abstract component that is used as superclass, will not be shown in style
guide */

<script>
import _formGroup from './_formGroup.vue'

export default {
  components: {
    'form-group': _formGroup
  },
  props: {
    /** value to be shown as placeholder in the input (if possible) */
    placeholder: String,
    /** label to be shown above the input */
    label: String,
    /** optional help string shown below input */
    help: String,
    /** whether input can nullable (does not validate, but show option to clear input) */
    nullable: {
      type: Boolean,
      default: false
    },
    /** wheter input is readonly (default: false) */
    readonly: {
      type: Boolean,
      default: false
    },
    /** message when in error state */
    error: null,
    /** default value */
    defaultValue: null
  },
  data: function() {
    return {
      /** unique identifier, autogenerated */
      id: null,
      /** value */
      value: null
    }
  },
  watch: {
    value() {
      this.$emit('input', this.value)
    }
  },
  // generate automatic id
  mounted() {
    this.id = Math.random()
      .toString(36)
      .substring(7)
  },
  // initialise with default value if exists
  created() {
    if (this.defaultValue != null) {
      this.value = this.defaultValue
    }
  }
}
</script>
