[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "molgenis-emx2-client-py"
version = "8.185.0"
description = "Python client for the MOLGENIS EMX2 API"
dependencies = [
    'requests==2.31.0',
    'python-dotenv==1.0.0',
    'setuptools==67.8.0',
    'tomli==2.0.1',
]
requires-python = ">=3.11"
