apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  initContainers:
    - name: initdb
      image: busybox
      command:
        - wget
        - "-O"
        - "/docker-entrypoint-initdb.d/initdb.sql"
        - https://raw.githubusercontent.com/molgenis/molgenis-emx2/master/.docker/initdb.sql
      volumeMounts:
        - name: postgres-initdb
          mountPath: /docker-entrypoint-initdb.d
  containers:
    - name: java
      image: gradle:jdk16-hotspot
      imagePullPolicy: IfNotPresent
      command:
      - cat
      tty: true
      resources:
        requests:
          cpu: 2
          memory: 2Gi
    - name: postgres
      image: postgres:13-alpine
      imagePullPolicy: IfNotPresent
      args: ["-c", "shared_buffers=256MB", "-c", "max_locks_per_transaction=1024"]
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 1Gi
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
      volumeMounts:
        - name: postgres-initdb
          mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: postgres-initdb
      emptyDir: {}
  restartPolicy: Never
