apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
spec:
  containers:
    - name: java
      image: gradle:jdk17
      imagePullPolicy: IfNotPresent
      command:
      - cat
      tty: true
      resources:
        requests:
          cpu: 2
          memory: 2Gi
    - name: postgres
      image: postgres:14-alpine
      imagePullPolicy: IfNotPresent
      args: ["-c", "shared_buffers=256MB", "-c", "max_locks_per_transaction=1024"]
      tty: true
      resources:
        requests:
          cpu: 1
          memory: 1Gi
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
  volumes:
    - name: postgres-initdb
      emptyDir: {}
  restartPolicy: Never
