dependencies {
    implementation project(':backend:molgenis-emx2-sql')
    implementation project(':backend:molgenis-emx2-io')
    implementation project(':backend:molgenis-emx2-graphql')
    implementation project(':backend:molgenis-emx2')
    implementation project(':backend:molgenis-emx2-datamodels')
    implementation project(':backend:molgenis-emx2-rdf')
    implementation project(':backend:molgenis-emx2-beacon-v2')
    implementation project(':backend:molgenis-emx2-cafevariome')
    implementation project(':backend:molgenis-emx2-fairdatapoint')
    implementation project(':backend:molgenis-emx2-tasks')
    implementation project(':backend:molgenis-emx2-email')
    implementation project(':backend:molgenis-emx2-analytics')

    implementation libs.polyglot
    implementation libs.swagger.parser
    implementation libs.okhttp
    implementation libs.okhttp.brotli
    implementation libs.sitemapgen4j
    implementation libs.sass.embedded.host
    implementation libs.caffeine
    implementation libs.bundles.prometheus

    testImplementation libs.rest.assured
    testImplementation libs.bundles.poi
    testImplementation libs.zip4j
    testImplementation libs.system.stubs.jupiter
    testImplementation libs.junit.jupiter

    testFixturesApi project(':backend:molgenis-emx2-sql')
    testFixturesApi project(':backend:molgenis-emx2')
    testFixturesApi libs.rest.assured
    testFixturesImplementation libs.system.stubs.jupiter
}

tasks.register('dev', JavaExec) {
    group = 'application'
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('org.molgenis.emx2.RunMolgenisEmx2')
    rootProject.ext.applyDotenvHeap(it)
}
