dependencies {
    implementation project(':backend:molgenis-emx2-sql')
    implementation project(':backend:molgenis-emx2-io')
    implementation project(':backend:molgenis-emx2-graphql')
    implementation project(':backend:molgenis-emx2')
    implementation project(':backend:molgenis-emx2-datamodels')
    implementation project(':backend:molgenis-emx2-rdf')
    implementation project(':backend:molgenis-emx2-beacon-v2')
    implementation project(':backend:molgenis-emx2-cafevariome')
    implementation project(':backend:molgenis-emx2-fairdatapoint')
    implementation project(':backend:molgenis-emx2-tasks')
    implementation project(':backend:molgenis-emx2-email')
    implementation project(':backend:molgenis-emx2-analytics')

    implementation 'org.graalvm.polyglot:polyglot:25.2.4'
    implementation group: 'io.swagger.parser.v3', name:'swagger-parser', version:swaggerParserVersion
    implementation group: 'com.squareup.okhttp3', name:'okhttp', version:squareupVersion
    implementation group: 'com.squareup.okhttp3', name:'okhttp-brotli', version:squareupVersion
    implementation group: 'com.github.dfabulich', name:'sitemapgen4j', version:sitemapgen4jVersion
    implementation group: 'de.larsgrefer.sass', name:'sass-embedded-host', version:sassEmbeddedHostVersion
    implementation group: 'com.github.ben-manes.caffeine', name:'caffeine', version:caffeineVersion

    implementation group: 'io.prometheus', name:'prometheus-metrics-core', version:prometheusVersion
    implementation group: 'io.prometheus', name:'prometheus-metrics-instrumentation', version:prometheusVersion
    implementation group: 'io.prometheus', name:'prometheus-metrics-exporter-httpserver', version:prometheusVersion
    implementation group: 'io.prometheus', name:'prometheus-metrics-exporter-servlet-jakarta', version:prometheusVersion

    testImplementation group: 'io.rest-assured', name:'rest-assured', version:restAssuredVersion
    testImplementation group: 'org.apache.poi', name:'poi', version:poiVersion
    testImplementation group: 'org.apache.poi', name:'poi-ooxml', version:poiVersion
    testImplementation group: 'net.lingala.zip4j', name:'zip4j', version:zip4jVersion
    testImplementation group: 'uk.org.webcompere', name:'system-stubs-jupiter', version:systemStubsJupiterVersion
    testImplementation group: 'org.junit.jupiter', name:'junit-jupiter', version:junitVersion

    testFixturesApi project(':backend:molgenis-emx2-sql')
    testFixturesApi project(':backend:molgenis-emx2')
    testFixturesApi group: 'io.rest-assured', name:'rest-assured', version:restAssuredVersion

    testFixturesImplementation group: 'uk.org.webcompere', name:'system-stubs-jupiter', version:systemStubsJupiterVersion
}

tasks.register('dev', JavaExec) {
    group = 'application'
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set('org.molgenis.emx2.RunMolgenisEmx2')
    rootProject.ext.applyDotenvHeap(it)
}
