apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE {{ .Values.database.name }};
    CREATE USER {{ .Values.database.username }}  WITH LOGIN NOSUPERUSER INHERIT CREATEROLE ENCRYPTED PASSWORD '{{ .Values.database.password }}';
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.database.name }} TO {{ .Values.database.username }};
