apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "emx2.fullname" . }}-postgres-pv
  labels:
    app: {{ template "emx2.name" . }}
    chart: {{ template "emx2.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
