package org.molgenis.emx2.io.legacy;

public enum AttributesFileHeader {
    ENTITY, NAME, DATATYPE, REFENTITY, NILLABLE, IDATTRIBUTE, DESCRIPTION, RANGEMIN, RANGEMAX, LABEL, AGGREGATEABLE, LABELATTRIBUTE, READONLY, VALIDATIONEXPRESSION, TAGS, VISIBLE, DEFAULTVALUE, PARTOFATTRIBUTE, EXPRESSION;
}
