dependencies {
    implementation group: 'com.github.ben-manes.caffeine', name:'caffeine', version:caffeineVersion
    implementation group: 'org.graalvm.js', name:'js', version:graalvmVersion
    implementation group: 'org.graalvm.js', name:'js-language', version:graalvmVersion
    implementation group: 'org.graalvm.js', name:'js-scriptengine', version:graalvmVersion
    testImplementation group: 'io.javalin', name:'javalin-testtools', version:javalinVersion
}
