dependencies {
    implementation 'com.github.ben-manes.caffeine:caffeine:3.3.0'
    implementation 'org.graalvm.js:js:25.4.4.1.1'
    implementation 'org.graalvm.js:js-language:25.4.4.1.1'
    implementation 'org.graalvm.js:js-scriptengine:25.4.4.1.1'
    testImplementation 'io.javalin:javalin-testtools:6.7.0'
}
