// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/:schema/api/file/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/[schema]/api/file/[...]').default>>>>
    }
    '/:schema/api/message': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/[schema]/api/message').default>>>>
    }
    '/:schema/api/trigger': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/[schema]/api/trigger').default>>>>
    }
    '/:schema/graphql': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/[schema]/graphql').default>>>>
    }
    '/graphql': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../tailwind-components/server/routes/graphql').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}