dependencies {
    implementation project(':backend:molgenis-emx2')
    implementation project(':backend:molgenis-emx2-graphql')
    implementation project(':backend:molgenis-emx2-sql')

    implementation group: 'org.eclipse.rdf4j', name:'rdf4j-sparqlbuilder', version:rdf4jVersion
    implementation group: 'org.eclipse.rdf4j', name:'rdf4j-queryresultio-text', version:rdf4jVersion

    testImplementation project(':backend:molgenis-emx2-io')
    testImplementation project(':backend:molgenis-emx2-tasks')
    testImplementation project(':backend:molgenis-emx2-datamodels')

    testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-sparqlbuilder', version:rdf4jVersion
    testFixturesImplementation group: 'org.eclipse.rdf4j', name:'rdf4j-queryresultio-text', version:rdf4jVersion
    testFixturesImplementation project(':backend:molgenis-emx2')
}
//we use shacls from data folder
processResources{
    from("$rootDir/data/_shacl"){
        into ("_shacl")
    }
}
