query RepeatedVariables($filter: RepeatedVariablesFilter) {
  RepeatedVariables(filter: $filter) {
    resource {
      id
    }
    dataset {
      resource {
        id
      }
      name
    }
    name
  }
}