query SubcohortCounts($filter: SubcohortCountsFilter) {
  SubcohortCounts(filter: $filter) {
    subcohort {
      resource {
        id
      }
      name
    }
    ageGroup {
      name
    }
    nTotal
    nMale
    nFemale
  }
}
