query VariableMappings($filter: VariableMappingsFilter) {
  VariableMappings(filter: $filter) {
    source{
      id
    }
    sourceDataset{
      name
    }
    sourceVariables{
      resource{
        id
      }
    }
    sourceVariablesOtherDatasets{
      resource{
        id
      }
    }
    target{
      id
    }
    targetDataset{
      name
    }
    targetVariable{
      resource{
        id
      }
      name
    }
    match{
      name
    }
    status{
      name
    }

  }
}