// Shared ESLint flat config for the EMX2 frontend workspace.
// Packages run `eslint .` from their own directory; ESLint finds this config
// by searching ancestor directories.
//
// Scope is deliberately minimal: it enforces the naming conventions from
// docs/molgenis/dev_guidelines.md ("Naming conventions") and nothing else.
// Formatting is handled by prettier, type errors by `nuxi typecheck`.
import tseslint from "typescript-eslint";
import vueParser from "vue-eslint-parser";

// Pre-existing lowercase type names, exempted so the rule can be an error for
// all new code. Rename these over time and shrink this list; do not add to it.
const grandfatheredTypeNames = [
  "sortDirection",
  "schemaId",
  "cellPayload",
  "columnId",
  "columnValue",
  "recordValue",
  "fileValue",
  "view",
  "filterRefField",
  "activeTabType",
  "linkTarget",
  "analyticsService",
  "optionsFetchFn",
];

// Files generated by Generator.java embed schema table names (e.g.
// ICatalogueOntologies_Themes_agg) and are not subject to naming rules.
const generatedFiles = [
  "tailwind-components/types/cms.ts",
  "metadata-utils/src/viz/ErnDashboard.ts",
  "nestor-public/src/types/schema.ts",
  "cranio-provider/src/types/schema.ts",
  "cranio-provider/src/types/ErnDashboard.ts",
  "directory/src/interfaces/directory.ts",
  "catalogue/interfaces/catalogue.ts",
];

export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/.nuxt/**",
      "**/.output/**",
      "**/dist/**",
      "**/coverage/**",
      "**/*.d.ts",
      ...generatedFiles,
    ],
  },
  {
    // Stale disable-directives are expected: this config runs only a minimal
    // ruleset, so directives for rules that are not enabled here must not warn.
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
  },
  {
    files: ["**/*.ts", "**/*.mts", "**/*.vue"],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
        extraFileExtensions: [".vue"],
        ecmaVersion: "latest",
        sourceType: "module",
      },
    },
    plugins: {
      "@typescript-eslint": tseslint.plugin,
    },
    rules: {
      // Type-like identifiers (type aliases, interfaces, enums, type params)
      // are PascalCase. Properties are intentionally not constrained: the `_`
      // prefix for client-synthesized fields (e.g. _rowId) and API meta
      // fields (_agg, mg_insertedBy, ...) must remain valid.
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "typeLike",
          format: ["PascalCase"],
          filter: {
            regex: `^(${grandfatheredTypeNames.join("|")})$`,
            match: false,
          },
        },
      ],
    },
  },
];
