packages:
  - metadata-utils
  - molgenis-components
  - emx2-analytics
  - helloworld
  - hpc
  - settings
  - central
  - schema
  - tables
  - updownload
  - pages
  - graphql-playground
  - tailwind-components
  - catalogue
  - molgenis-viz
  - cranio-public
  - cranio-provider
  - ern-genturis
  - ern-ithaca
  - ern-reconnet
  - ern-skin
  - nestor-public
  - reports
  - tasks
  - gportal
  - projectmanager
  - aggregates
  - directory
  - ui

overrides:
  cookie@<0.7.0: '>=0.7.0'
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.25.0'
  h3@<=1.15.4: '>=1.15.5'
  jsonpath@<1.2.0: '>=1.2.0'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  qs@<6.14.1: '>=6.14.1'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  undici@<6.23.0: '>=6.23.0'
