packages:
- metadata-utils
- molgenis-components
- emx2-analytics
- helloworld
- settings
- central
- schema
- tables
- updownload
- pages
#- graphql-playground
- tailwind-components
- catalogue
- molgenis-viz
- cranio-public
- cranio-provider
- ern-genturis
- ern-ithaca
- ern-reconnet
- ern-skin
- nestor-public
- reports
- tasks
- gportal
- projectmanager
- aggregates
- directory
- ui