packages:
# big shared libs should build first
- metadata-utils
- tailwind-components
- molgenis-components
# then the apps
- aggregates
- catalogue
- central
- cranio-provider
  imdhub-public
- directory
- emx2-analytics
- ern-genturis
- ern-ithaca
- ern-reconnet
- ern-skin
- gportal
- graphql-playground
- helloworld
- molgenis-viz
- nestor-public
- pages
- projectmanager
- reports
- schema
- settings
- tables
- tasks
- ui
- updownload

# pnpm nx run-many --target=build --all --parallel

# pnpm nx run-many --target=build --all --skip-nx-cache --parallel