table: Profiles
description: INTEGRATE
profiles:
- integrate
columns:
- name: DataCatalogueFlat
  description: DataCatalogueFlat
  profiles:
  - datacatalogueflat
- name: EMA
  description: EMA
  profiles:
  - ema
- name: RWEStaging
  description: RWEStaging
  profiles:
  - rwestaging
- name: CohortsStaging
  description: CohortsStaging
  profiles:
  - cohortsstaging
- name: UMCGCohortsStaging
  description: UMCGCohortsStaging
  profiles:
  - umcgcohortsstaging
- name: NetworksStaging
  description: NetworksStaging
  profiles:
  - networksstaging
- name: UMCUCohorts
  description: UMCUCohorts
  profiles:
  - umcucohorts
- name: INTEGRATE
  description: INTEGRATE
