table: Profiles
description: INTEGRATE
profiles: [integrate]
columns:
  DataCatalogueFlat:
    profiles: [catalogue_core]
    description: DataCatalogueFlat
  EMA:
    profiles: [ema]
    description: EMA
  RWEStaging:
    profiles: [rwe_staging]
    description: RWEStaging
  CohortsStaging:
    profiles: [cohorts_staging]
    description: CohortsStaging
  UMCGCohortsStaging:
    profiles: [umcg_cohorts_staging]
    description: UMCGCohortsStaging
  NetworksStaging:
    profiles: [networks_staging]
    description: NetworksStaging
  UMCUCohorts:
    profiles: [umcu_cohorts]
    description: UMCUCohorts
  INTEGRATE:
    profiles: [integrate]
    description: INTEGRATE
