table: Variable values
description: Listing of categorical value+label definition in case of a categorical variable
profiles: [catalogue_core]
columns:
  resource:
    type: ref
    key: 1
    required: true
    refTable: Resources
    description: Resource the variable belongs to
  dataset:
    type: ref
    key: 1
    required: true
    refTable: Datasets
    refLink: resource
    description: Dataset the variable belongs to
  variable:
    type: ref
    key: 1
    required: true
    refTable: Variables
    refLink: dataset
    description: Variable name
  value:
    key: 1
    required: true
    description: Variable value, e.g. '1'
  label:
    required: true
    description: Variable label, e.g. 'Yes'
  order:
    type: int
    description: Order that the variable values should be displayed in
  is missing:
    type: bool
    description: Whether this variable value indicates that data is missing, e.g. '-1' for 'NA'
  ontology term URI:
    description: Reference to ontology term that defines this categorical value
  since version:
    description: When this variable value was introduced, if applicable
  until version:
    description: When this variable value was removed, if applicable
