plugins {
    id 'base'
}

tasks.register('generateSearchPaths') {
    def output = file("search-paths.js")

    doLast {
        def paths = ['molgenis', 'catalogue', 'directory']
            .collectMany { dir ->
                fileTree(dir) {
                    include '**/*.md'
                }.files.collect { f ->
                    f.path.replace(File.separator, '/').split("/docs/")[1]
                }
            }

        output.parentFile.mkdirs()
        output.text = "window.docsifySearchPaths = ${groovy.json.JsonOutput.toJson(paths)};"
    }
}

tasks.register('copyDistFiles', Copy) {
    dependsOn generateSearchPaths
    from "."
    exclude 'build'
    into "${project.layout.buildDirectory.get()}/resources/main/public_html/apps/${project.name}"
    outputs.dir("${project.layout.buildDirectory.get()}/resources/main/public_html/apps/${project.name}")
    outputs.cacheIf { true }
}

tasks.register('createJar', Zip) {
    dependsOn copyDistFiles
    archiveBaseName = 'molgenis-emx2-docs'
    archiveExtension = 'jar'
    destinationDirectory = layout.buildDirectory.dir("build/libs").get().asFile
    from('build/resources/main')
}

configurations {
    appResources
}
configurations.default.extendsFrom(configurations.appResources)

artifacts {
    appResources(createJar.getArchiveFile()) {
        builtBy createJar
        type = "jar"
    }
}
