name: preview
on:
  pull_request:
    branches: master
    types: [labeled]
jobs:
  create-preview:
    if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.AWS_SSH_KEY }}
          known_hosts: molgenis.org

      - name: Checkout out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: run build without tests, we only need the product jar
        run: ./gradlew build -x test
        env:
          JVM_OPTS: -Xmx3200m
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=4"

      - name: push to aws
        run: sh .aws/aws_start_preview_from_build.sh
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: eu-central-1

      - name: Post comment on the preview
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "Preview created for 60 mins at http://"$PUBLIC_DNS
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}