name: github/actions
on: 
  pull_request:
    branches: master
jobs:
  build: 
    runs-on: ubuntu-latest
    container: gradle:jdk16-hotspot

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get postgresql, git, docker
        run: |
           apt-get update && apt-get install postgresql-client git -y
           curl -fsSL https://get.docker.com -o get-docker.sh
           sh get-docker.sh

      - name: Initialize database
        run: psql -h postgres -p 5432 -U postgres < .docker/initdb.sql
        env:
          PGPASSWORD: postgres

      - name: Sign into docker
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}

      - name: dependencies
        run: ./gradlew dependencies

      - name: Build with run tests and sonar (add 'release' to also do releases, and jib to push docker)
        run: ./gradlew --stacktrace test jacocoMergedReport sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=molgenis -Dsonar.host.url=https://sonarcloud.io -Dorg.ajoberstar.grgit.auth.username=$GITHUB_TOKEN -Dorg.ajoberstar.grgit.auth.password
        env:
          MOLGENIS_POSTGRES_USER: molgenis_admin
          MOLGENIS_POSTGRES_PASS: molgenis_admin
          MOLGENIS_POSTGRES_URI: jdbc:postgresql://postgres/molgenisdb
          JVM_OPTS: -Xmx3200m
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
