name: preview
on:
  pull_request:
    branches: master
jobs:
  container-job: 
    runs-on: ubuntu-latest
    container: 
      image: gradle:jdk16-hotspot
      ports: 
        - 8080

    steps:
      - name: install aws
        uses: unfor19/install-aws-cli-action@v1

      - name: test aws
        run: aws s3 ls
        shell: bash
        env:
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Checkout out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: run build without tests, we only need the product jar
        run: ./gradlew build --no-daemon -x test
        env:
          JVM_OPTS: -Xmx3200m
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
