on:
  pull_request:
    types: [ closed ]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Build
        id: "delete-pr-preview"
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.2.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
