name: PR preview link
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
  preview-comment:
    # previews are only deployed for branches in this repo, not for forks
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment preview link on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          message: |
            **Preview:** https://preview-emx2-pr-${{ github.event.number }}.dev.molgenis.org/

            The preview is deployed by CircleCI and may take a while to become available after each push.
